PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX sim: <http://www.ifi.uio.no/IN3060/simpsons#> 
PREFIX fam: <http://www.ifi.uio.no/IN3060/family#> 

SELECT DISTINCT ?aname ?bname
       WHERE {
          ?a fam:hasMother ?b .
          ?a foaf:name ?aname .
          ?b foaf:name ?bname .
       }
